version: "3.8"
services:
  mongodb:
    container_name: mongo
    deploy:
      replicas: 3  # Creates 3 replicas of the backend container
    image: mongo:latest
    volumes:
      - ./backend/data:/data
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    deploy:
      replicas: 3  # Creates 3 replicas of the backend container
    build: ./backend
    env_file:
      - ./backend/.env.docker
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    deploy:
      replicas: 2  # Creates 3 replicas of the backend container
    build: ./frontend
    env_file:
      - ./frontend/.env.docker
    ports:
      - "5173:5173"

  redis:
    container_name: redis
    deploy:
      replicas: 3  # Creates 3 replicas of the backend container
    restart: unless-stopped
    image: redis:7.0.5-alpine 
    expose:
        - 6379
    depends_on:
      - mongodb

volumes:
  data:
